import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// import { PHProvider } from '../components/posthog/providers'
// import dynamic from 'next/dynamic'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const PostHogPageView = dynamic(() => import('../components/posthog/PostHogPageView'), {
//   ssr: false,
// })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <PHProvider>
        <body className={inter.className}>
          <PostHogPageView /> 
          {children}
        </body>
      </PHProvider> */}
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
